// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNXhGeswJOwiz-ZAfqCYMqBeTK5bT3seE',
    appId: '1:8771795291:web:67941b87fd628cc22e027e',
    messagingSenderId: '8771795291',
    projectId: 'dummy-96f0f',
    authDomain: 'dummy-96f0f.firebaseapp.com',
    databaseURL: 'https://dummy-96f0f-default-rtdb.firebaseio.com',
    storageBucket: 'dummy-96f0f.appspot.com',
    measurementId: 'G-KD1W2E4G5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCQdUsQOV-vedMWfCdMbRRqr_ed0S8s_o',
    appId: '1:8771795291:android:8614bc17b5b6294c2e027e',
    messagingSenderId: '8771795291',
    projectId: 'dummy-96f0f',
    databaseURL: 'https://dummy-96f0f-default-rtdb.firebaseio.com',
    storageBucket: 'dummy-96f0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDch5i58n8Wa0zCuJoNfu2xyz5W3W4UUNo',
    appId: '1:8771795291:ios:7cca9321b3aae6eb2e027e',
    messagingSenderId: '8771795291',
    projectId: 'dummy-96f0f',
    databaseURL: 'https://dummy-96f0f-default-rtdb.firebaseio.com',
    storageBucket: 'dummy-96f0f.appspot.com',
    iosBundleId: 'com.example.newFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDch5i58n8Wa0zCuJoNfu2xyz5W3W4UUNo',
    appId: '1:8771795291:ios:aa2c146ba283f5372e027e',
    messagingSenderId: '8771795291',
    projectId: 'dummy-96f0f',
    databaseURL: 'https://dummy-96f0f-default-rtdb.firebaseio.com',
    storageBucket: 'dummy-96f0f.appspot.com',
    iosBundleId: 'com.example.newFirebaseProject.RunnerTests',
  );
}
